[package]
name = "gnostr-tui"
authors = ["gnostr <admin@gnostr.org>", "extrawurst <mail@rusticorn.com>"]
description = "blazing fast terminal-ui for git"
exclude = [".github/*", ".vscode/*", "assets/*"]
readme = "README.md"
categories = ["command-line-utilities"]

version = { workspace = true }
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
documentation = { workspace = true }
keywords = { workspace = true }

## git tui
[[bin]]
name = "git-tui"
path = "src/main.rs"

## gnostr-tui
[[bin]]
name = "gnostr-tui"
path = "src/main.rs"

[dependencies]
anyhow = "1.0"
asyncgit = { path = "./asyncgit", default-features = false }
backtrace = "0.3"
bitflags = "1.3"
bugreport = "0.5"
bwrap = { version = "1.3.0", features = ["use_std"] }
bytesize = { version = "1.3", default-features = false }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
clap = { version = "4.4", features = ["env", "cargo"] }
crossbeam-channel = "0.5"
crossterm = { version = "0.26.1", features = ["serde"] }
dirs = "5.0"
easy-cast = "0.5"
filetreelist = { path = "./filetreelist" }
fuzzy-matcher = "0.3"
gh-emoji = { version = "1.0", optional = true }
git-version = { path = "vendor/git-version" }
git2 = { version = "0.18.0" }
indexmap = "1.9"
itertools = "0.12"
log = "0.4"
notify = "5.1"
notify-debouncer-mini = "0.2"
once_cell = "1"
ratatui = { version = "0.21", default-features = false, features = ['crossterm', 'serde'] }
rayon-core = "1.11"
ron = "0.8"
scopeguard = "1.2"
scopetime = { path = "./scopetime" }
serde = "1.0"
shellexpand = "3.1"
simplelog = { version = "0.12", default-features = false }
struct-patch = "0.2"
syntect = { version = "5.0", default-features = false, features = ["parsing", "default-syntaxes", "default-themes", "html"] }
unicode-segmentation = "1.10"
unicode-truncate = "0.2"
unicode-width = "0.1"
which = "4.4"

[package.metadata.cargo-udeps.ignore]
normal = ["cargo-audit"]
development = ["cargo-audit"]
#build = []

[dev-dependencies]
cargo-audit = { version = "0.18.3", features = ["binary-scanning"] }
pretty_assertions = "1.4"
tempfile = "3.4"

[badges]
maintenance = { status = "actively-developed" }

[features]
default = ["ghemoji", "regex-fancy", "trace-libgit", "vendor-openssl"]
ghemoji = ["gh-emoji"]
# regex-* features are mutually exclusive.
regex-fancy = ["syntect/regex-fancy"]
regex-onig = ["syntect/regex-onig"]
timing = ["scopetime/enabled"]
trace-libgit = ["asyncgit/trace-libgit"]
vendor-openssl = ["asyncgit/vendor-openssl"]

#[workspace]
#members = ["asyncgit", "filetreelist", "git2-hooks", "git2-testing", "scopetime"]

## [profile.release]
## lto = true
## opt-level = 'z'   # Optimize for size.
## codegen-units = 1
##
## # make debug build as fast as release
## # usage of utf8 encoding inside tui
## # makes their debug profile slow
## [profile.dev.package."ratatui"]
## opt-level = 3
##
## #[workspace]
