# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.29.0/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.29.0/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/randymcmillan/dotfiles/nostril

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/randymcmillan/dotfiles/nostril

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.29.0/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.29.0/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/randymcmillan/dotfiles/nostril/CMakeFiles /Users/randymcmillan/dotfiles/nostril//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/randymcmillan/dotfiles/nostril/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named configurator

# Build rule for target.
configurator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 configurator
.PHONY : configurator

# fast build rule for target.
configurator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/configurator.dir/build.make CMakeFiles/configurator.dir/build
.PHONY : configurator/fast

#=============================================================================
# Target rules for targets named nostril

# Build rule for target.
nostril: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nostril
.PHONY : nostril

# fast build rule for target.
nostril/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nostril.dir/build.make CMakeFiles/nostril.dir/build
.PHONY : nostril/fast

#=============================================================================
# Target rules for targets named secp256k1_precomputed

# Build rule for target.
secp256k1_precomputed: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 secp256k1_precomputed
.PHONY : secp256k1_precomputed

# fast build rule for target.
secp256k1_precomputed/fast:
	$(MAKE) $(MAKESILENT) -f ext/secp256k1/src/CMakeFiles/secp256k1_precomputed.dir/build.make ext/secp256k1/src/CMakeFiles/secp256k1_precomputed.dir/build
.PHONY : secp256k1_precomputed/fast

#=============================================================================
# Target rules for targets named secp256k1

# Build rule for target.
secp256k1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 secp256k1
.PHONY : secp256k1

# fast build rule for target.
secp256k1/fast:
	$(MAKE) $(MAKESILENT) -f ext/secp256k1/src/CMakeFiles/secp256k1.dir/build.make ext/secp256k1/src/CMakeFiles/secp256k1.dir/build
.PHONY : secp256k1/fast

aes.o: aes.c.o
.PHONY : aes.o

# target to build an object file
aes.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nostril.dir/build.make CMakeFiles/nostril.dir/aes.c.o
.PHONY : aes.c.o

aes.i: aes.c.i
.PHONY : aes.i

# target to preprocess a source file
aes.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nostril.dir/build.make CMakeFiles/nostril.dir/aes.c.i
.PHONY : aes.c.i

aes.s: aes.c.s
.PHONY : aes.s

# target to generate assembly for a file
aes.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nostril.dir/build.make CMakeFiles/nostril.dir/aes.c.s
.PHONY : aes.c.s

base64.o: base64.c.o
.PHONY : base64.o

# target to build an object file
base64.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nostril.dir/build.make CMakeFiles/nostril.dir/base64.c.o
.PHONY : base64.c.o

base64.i: base64.c.i
.PHONY : base64.i

# target to preprocess a source file
base64.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nostril.dir/build.make CMakeFiles/nostril.dir/base64.c.i
.PHONY : base64.c.i

base64.s: base64.c.s
.PHONY : base64.s

# target to generate assembly for a file
base64.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nostril.dir/build.make CMakeFiles/nostril.dir/base64.c.s
.PHONY : base64.c.s

configurator.o: configurator.c.o
.PHONY : configurator.o

# target to build an object file
configurator.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/configurator.dir/build.make CMakeFiles/configurator.dir/configurator.c.o
.PHONY : configurator.c.o

configurator.i: configurator.c.i
.PHONY : configurator.i

# target to preprocess a source file
configurator.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/configurator.dir/build.make CMakeFiles/configurator.dir/configurator.c.i
.PHONY : configurator.c.i

configurator.s: configurator.c.s
.PHONY : configurator.s

# target to generate assembly for a file
configurator.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/configurator.dir/build.make CMakeFiles/configurator.dir/configurator.c.s
.PHONY : configurator.c.s

nostril.o: nostril.c.o
.PHONY : nostril.o

# target to build an object file
nostril.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nostril.dir/build.make CMakeFiles/nostril.dir/nostril.c.o
.PHONY : nostril.c.o

nostril.i: nostril.c.i
.PHONY : nostril.i

# target to preprocess a source file
nostril.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nostril.dir/build.make CMakeFiles/nostril.dir/nostril.c.i
.PHONY : nostril.c.i

nostril.s: nostril.c.s
.PHONY : nostril.s

# target to generate assembly for a file
nostril.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nostril.dir/build.make CMakeFiles/nostril.dir/nostril.c.s
.PHONY : nostril.c.s

sha256.o: sha256.c.o
.PHONY : sha256.o

# target to build an object file
sha256.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nostril.dir/build.make CMakeFiles/nostril.dir/sha256.c.o
.PHONY : sha256.c.o

sha256.i: sha256.c.i
.PHONY : sha256.i

# target to preprocess a source file
sha256.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nostril.dir/build.make CMakeFiles/nostril.dir/sha256.c.i
.PHONY : sha256.c.i

sha256.s: sha256.c.s
.PHONY : sha256.s

# target to generate assembly for a file
sha256.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/nostril.dir/build.make CMakeFiles/nostril.dir/sha256.c.s
.PHONY : sha256.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... configurator"
	@echo "... nostril"
	@echo "... secp256k1"
	@echo "... secp256k1_precomputed"
	@echo "... aes.o"
	@echo "... aes.i"
	@echo "... aes.s"
	@echo "... base64.o"
	@echo "... base64.i"
	@echo "... base64.s"
	@echo "... configurator.o"
	@echo "... configurator.i"
	@echo "... configurator.s"
	@echo "... nostril.o"
	@echo "... nostril.i"
	@echo "... nostril.s"
	@echo "... sha256.o"
	@echo "... sha256.i"
	@echo "... sha256.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

