name = "gnostr.org"
port = 2222

hostname = "gnostr.org"

[users.gnostr]
is_admin = true
can_create_repos = true
public_key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDWBy03xeN9LL4ZwqAOVcdrDBv26JQXPoIdQ+ZzCaf6LsW4DNNZlSn5GQwBZ340zC9os098ArH2dz5Hbih2x6tAAKdNRraG/CCc8JYe5ogitbPZlMaWcoeJkMLEiaZhJ8ZKBiTVw8tRHxIEGuuEEKXspsicE2WA7vf/Xv5jSKYEO5KUriz+JeOHTDD5C65AFh8odKI5Yb+sYRXT3tAdRTyOEJLfAdLQLRITyZ57eEBH3Ikkcpk3Ixoc/CBFGB45AQsi3X61djiRkAULilvAdTPfvgk2If0ldbEzHdLiHcbkanhW//xwrZ4GU6hjGjviSOq+n3Qki/InNxdJmh2jr7nJ4mdevctvtD3YLyVU+Ku99Y83lyMWWZ2LlRYK3OxK0fc9d7xJQVl9f4kPG3C6ZUcJ1BZbl/mCKOqegrTLnaTLj3wx3+NQSjzw9unhkVmcf7dofL+zYf2GLCiDKQrgVX9f4ZQr7mWi53QDwrZm0BMxDvERj7qJmwAmb1nUkBP6aJU= randymcmillan@DeepSpaceMBPro.local"

[users.gnostr-user]
can_create_repos = true
public_key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDaBogLsfsOkKIpZEZYa3Ee+wFaaxeJuHps05sH2rZLf+KEE6pWX5MT2iWMgP7ihmm6OqbAPkWoBUGEO5m+m/K1S0MgQXUvaTsTI0II3MDqJT/RXA6Z9c+ZIDROEAkNIDrfeU2n8hQXfMHwG6aJjwv3Zky9jR/ey2rSgKLMcTOLrMeAyop6fYhjIHqp0dTagHo1j+XHAbVsrjw6oxC0ohTkp8rzH6cYJyjK4TOKApEgCALJUOA2rbHNxr68wAIe2RS36dRQobD3ops2+HoOGk7pkBQazBAlZp/H4monWRrq7tTEw8FkGMX5udZQX6BNEI0vJZqtdkSpG7jSS3aL7GXcuOYKpsTKxuGm5BWsrRPiphsc25U02oe/y3+qM0ceP/njJp3ZvXQ/a2QGPU4+P8WSD+J0oKS+TiRKrpiTR4ChJk8zWupg4PI5zflN3yyK7MrGXg1n0DsvHxPXcqpvVRz4i8ORt6IlKGkve1tC0Wd9pVy4044LDethMORRZFjWAdS/caN1EMgTrrGMxi0DLVw6ahedGUgZj2WYWfsrEg8Kzbfk3fn32sO/lMnNyz5hmavMBiNORGlIi2Qe2RjQEtcJHn89B7UtyEfnj87V+jZYcFf4nnNQigT2eQ3NlB1YzZS4Zk/OxQeYypclzYFaiYc7RZv2yxKVOy0KvEpldyUKeQ== randy.lee.mcmillan@gmail.com"

[welcome_message]
welcome_message = "welcome to gnostr.org!"

[extra]
extra = "extra toml content!"
