name = "gnostr.org"
port = 2222
hostname = "gnostr.org"

[users.gnostr-user]
is_admin = false
can_create_repos = true
public_key = ""

[users.gnostr]
is_admin = true
can_create_repos = true
public_key = ""

[welcome_message]
welcome_message = "welcome to gnostr.org!"

[extra]
extra = "extra toml content!"
