[package]
name = "rustylib"
version = "953267.1868.494774"
edition = "2021"

[workspace]

[lib]
crate-type = ["cdylib", "staticlib"]
name = "rustylib"

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[dependencies]
gnostr-p2p = { package = "gnostr-p2p", path = "../../../p2p", version = ">=953267.1868.494774" }
gnostr-relay = { version = ">=953267.1868.494774", path = "../../../relay" }
uniffi = { version = "0.28.0", features = ["cli"] }

[build-dependencies]
uniffi = { version = "0.28.0", features = ["build"] }
