[package]
name = "rustylib"
version = "0.1.0"
edition = "2021"

[workspace]

[lib]
crate-type = ["cdylib", "staticlib"]
name = "rustylib"

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[dependencies]
gnostr-chat = { package = "gnostr-chat", path = "../../../chat", version = ">=949455.1873.486970" }
gnostr-p2p = { package = "gnostr-p2p", path = "../../../p2p", version = ">=949455.1873.486970", default-features = false }
gnostr-relay = { version = "949455.1873.486970", path = "../../../relay" }
tokio = { version = "1", features = ["sync"] }
uniffi = { version = "0.28.0", features = [ "cli" ] }

[build-dependencies]
uniffi = { version = "0.28.0", features = [ "build" ] }
