wss://relay.damus.io
wss://relay.snort.social
wss://nos.lol
wss://nostr.mutinywallet.com
wss://lightning.red/
wss://relay.sharegap.net/
wss://herbstmeister.com/
wss://ngit.danconwaydev.com/
wss://blossom.gnostr.cloud/
wss://relay.ngit.dev/
wss://inner.sebastix.social/
