#!/usr/bin/env bash
set -euo pipefail

BASH_VERSION_CURRENT="${BASH_VERSION:-unknown}"
BASH_MAJOR="${BASH_VERSINFO[0]:-0}"
BASH_MINOR="${BASH_VERSINFO[1]:-0}"
if ! bash -n "${BASH_SOURCE[0]}"; then
  exit 1
fi

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

HOOKS_DIR=""
FORCE=false
UNINSTALL=false
LIST=false
SET_CORE_HOOKS_PATH=false

HOOK_NAMES=(
  applypatch-msg
  pre-applypatch
  post-applypatch
  pre-commit
  pre-merge-commit
  prepare-commit-msg
  commit-msg
  post-commit
  pre-rebase
  post-rewrite
  post-checkout
  post-merge
  pre-push
  pre-auto-gc
  sendemail-validate
  update
  post-update
  pre-receive
  post-receive
  proc-receive
  push-to-checkout
  reference-transaction
)

usage() {
  cat <<'EOF'
Usage: git-install-hooks.sh [--hooks-dir PATH] [--force] [--uninstall] [--list] [--set-core-hooks-path]

Options:
  --hooks-dir PATH           Install hooks into PATH instead of .git/hooks
  --force                    Overwrite existing hook files
  --uninstall                Remove installed stubs instead of creating them
  --list                     Print the standard hook names and exit
  --set-core-hooks-path      Set local core.hooksPath to the install directory
  --help                     Show this help
EOF
}

hook_description() {
  case "$1" in
    applypatch-msg) echo "runs before a patch message is applied" ;;
    pre-applypatch) echo "runs before git am finalizes an applypatch" ;;
    post-applypatch) echo "runs after git am applies a patch" ;;
    pre-commit) echo "runs before a commit is created" ;;
    pre-merge-commit) echo "runs before git creates a merge commit" ;;
    prepare-commit-msg) echo "runs before the commit message editor opens" ;;
    commit-msg) echo "runs after the commit message is prepared" ;;
    post-commit) echo "runs after a commit finishes" ;;
    pre-rebase) echo "runs before a rebase starts" ;;
    post-rewrite) echo "runs after history rewrite commands complete" ;;
    post-checkout) echo "runs after checkout or branch switching" ;;
    post-merge) echo "runs after a merge completes" ;;
    pre-push) echo "runs before refs are pushed" ;;
    pre-auto-gc) echo "runs before auto garbage collection" ;;
    sendemail-validate) echo "runs while git send-email validates messages" ;;
    update) echo "runs once per ref on the server side" ;;
    post-update) echo "runs after refs are updated on the server side" ;;
    pre-receive) echo "runs before refs are accepted on the server side" ;;
    post-receive) echo "runs after refs are accepted on the server side" ;;
    proc-receive) echo "runs for custom server-side ref processing" ;;
    push-to-checkout) echo "runs when a push updates the checked-out worktree" ;;
    reference-transaction) echo "runs around batches of ref updates" ;;
    *) echo "git hook" ;;
  esac
}

render_hook() {
  local hook_name="$1"
  local hook_path="$2"
  cat <<EOF
#!/usr/bin/env sh
# gnostr managed Git hook stub
# Hook: $hook_name
# Purpose: $(hook_description "$hook_name")
#
# This file is generated by scripts/git-install-hooks.sh.
# Replace the body with your own hook logic if you want this hook to do work.

gnostr_bin() {
  if command -v gnostr >/dev/null 2>&1; then
    command -v gnostr
    return 0
  fi
  if command -v gnostr.exe >/dev/null 2>&1; then
    command -v gnostr.exe
    return 0
  fi
  if command -v where >/dev/null 2>&1; then
    where gnostr 2>/dev/null | head -n 1
    return 0
  fi
  return 1
}

GNOSTR_BIN="\$(gnostr_bin || true)"
if [ -n "\$GNOSTR_BIN" ]; then
  :
fi

exit 0
EOF
  chmod +x "$hook_path"
}

resolve_git_dir() {
  local git_dir
  git_dir="$(git rev-parse --git-dir)"
  case "$git_dir" in
    /*) printf '%s\n' "$git_dir" ;;
    *) printf '%s\n' "$ROOT_DIR/$git_dir" ;;
  esac
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --hooks-dir)
      shift
      [[ $# -gt 0 ]] || { echo "--hooks-dir requires a value" >&2; exit 1; }
      HOOKS_DIR="$1"
      ;;
    --hooks-dir=*)
      HOOKS_DIR="${1#*=}"
      ;;
    --force)
      FORCE=true
      ;;
    --uninstall)
      UNINSTALL=true
      ;;
    --list)
      LIST=true
      ;;
    --set-core-hooks-path)
      SET_CORE_HOOKS_PATH=true
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "Unsupported argument: $1" >&2
      exit 1
      ;;
  esac
  shift
done

if [[ "$LIST" == true ]]; then
  printf '%s\n' "${HOOK_NAMES[@]}"
  exit 0
fi

if [[ -z "$HOOKS_DIR" ]]; then
  HOOKS_DIR="$(resolve_git_dir)/hooks"
fi

mkdir -p "$HOOKS_DIR"

if [[ "$UNINSTALL" == true ]]; then
  for hook_name in "${HOOK_NAMES[@]}"; do
    rm -f "$HOOKS_DIR/$hook_name"
  done
  if [[ "$SET_CORE_HOOKS_PATH" == true ]]; then
    git config --local --unset core.hooksPath || true
  fi
  exit 0
fi

for hook_name in "${HOOK_NAMES[@]}"; do
  hook_path="$HOOKS_DIR/$hook_name"
  if [[ -e "$hook_path" && "$FORCE" != true ]]; then
    printf 'skip existing %s\n' "$hook_path"
    continue
  fi
  render_hook "$hook_name" "$hook_path" >"$hook_path"
done

if [[ "$SET_CORE_HOOKS_PATH" == true ]]; then
  git config --local core.hooksPath "$HOOKS_DIR"
fi
