#!/usr/bin/env bash

BASH_VERSION_CURRENT="${BASH_VERSION:-unknown}"
BASH_MAJOR="${BASH_VERSINFO[0]:-0}"
BASH_MINOR="${BASH_VERSINFO[1]:-0}"
if ! bash -n "${BASH_SOURCE[0]}"; then
  exit 1
fi

BUMP_TYPE=${1:-patch}

gh workflow run publish.yml -f bump="$BUMP_TYPE"
