const KIND_REPO_ANNOUNCE = 30617;
const KIND_REPO_STATE_ANNOUNCE = 30618;
const KIND_REPO_PATCH = 1617;
const KIND_REPO_PULL_REQ = 1618;
const KIND_REPO_PULL_REQ_UPDATE = 1619;
const KIND_REPO_ISSUE = 1620;
const KIND_REPO_STATUS_OPEN = 1630;
const KIND_REPO_STATUS_APPLIED = 1631;
const KIND_REPO_STATUS_CLOSED = 1632;
const KIND_REPO_STATUS_DRAFT = 1633;
const KIND_RELAY_LIST = 10002;

const NIP34_REPO_KINDS = [
	KIND_REPO_ANNOUNCE,
	KIND_REPO_STATE_ANNOUNCE,
	KIND_REPO_PATCH,
	KIND_REPO_PULL_REQ,
	KIND_REPO_PULL_REQ_UPDATE,
	KIND_REPO_ISSUE,
	KIND_REPO_STATUS_OPEN,
	KIND_REPO_STATUS_APPLIED,
	KIND_REPO_STATUS_CLOSED,
	KIND_REPO_STATUS_DRAFT,
];

const NIP_34_KINDS = [...NIP34_REPO_KINDS, KIND_RELAY_LIST];

function is_nip34_repo_kind(kind) {
	return NIP34_REPO_KINDS.includes(kind);
}
