name: 'windows-vcpkg-action'
description: 'Setup vcpkg, OpenSSL, and Perl for Windows builds'
runs:
  using: 'composite'
  steps:
    - name: Set VCPKG_ROOT env
      shell: pwsh
      run: echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" | Out-File -FilePath $env:GITHUB_ENV -Append
    - name: Install OpenSSL with vcpkg
      shell: pwsh
      run: vcpkg install openssl:${{ inputs.arch }}-windows-static-md
    - name: Install Strawberry Perl
      shell: pwsh
      run: |
        choco install strawberryperl -y
        echo "C:\Strawberry\perl\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        echo "C:\Strawberry\c\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      if: runner.os == 'windows'
    - name: Install Perl modules
      shell: pwsh
      run: perl -MCPAN -e "install Locale::Maketext::Simple"
      if: runner.os == 'windows'
inputs:
  arch:
    description: 'Target architecture (e.g., x64)'
    required: true
